/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './apps/web/src/**/*.{html,ts,scss}',
    './libs/ui/src/**/*.{html,ts,scss,css}',
  ],
  theme: {
    extend: {
      colors: {
        ns: {
          bg:           'var(--ns-color-bg)',
          foreground:   'var(--ns-color-foreground)',
          canvas:       'var(--ns-color-canvas)',
          canvasSubtle: 'var(--ns-color-canvas-subtle)',
          card:         'var(--ns-color-card)',
          cardElevated: 'var(--ns-color-card-elevated)',
          text:         'var(--ns-color-text)',
          muted:        'var(--ns-color-muted)',
          mutedLight:   'var(--ns-color-muted-light)',
          border:       'var(--ns-color-border)',
          borderMuted:  'var(--ns-color-border-muted)',
          borderStrong: 'var(--ns-color-border-strong)',
          nav:          'var(--ns-color-nav)',
          primary:      'var(--ns-color-primary)',
          primaryHover: 'var(--ns-color-primary-hover)',
          primarySoft:  'var(--ns-color-primary-soft)',
          success:      'var(--ns-color-success)',
          successHover: 'var(--ns-color-success-hover)',
          successSoft:  'var(--ns-color-success-soft)',
          danger:       'var(--ns-color-danger)',
          dangerHover:  'var(--ns-color-danger-hover)',
          dangerSoft:   'var(--ns-color-danger-soft)',
          warning:      'var(--ns-color-warning)',
          warningRaw:   'var(--ns-color-warning-raw)',
          warningSoft:  'var(--ns-color-warning-soft)',
          accent:       'var(--ns-color-accent)',
          accentSoft:   'var(--ns-color-accent-soft)',
          purple:       'var(--ns-color-purple)',
          purpleSoft:   'var(--ns-color-purple-soft)',
          focus:        'var(--ns-color-focus)',
          // Illustration palette
          illusBlue:    'var(--ns-color-illus-blue)',
          illusYellow:  'var(--ns-color-illus-yellow)',
          illusGreen:   'var(--ns-color-illus-green)',
          illusRed:     'var(--ns-color-illus-red)',
          illusPurple:  'var(--ns-color-illus-purple)',
          illusTeal:    'var(--ns-color-illus-teal)',
          illusOrange:  'var(--ns-color-illus-orange)',
        },
      },
      fontFamily: {
        sans: [
          'Google Sans',
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'sans-serif',
        ],
      },
      spacing: {
        18: '4.5rem',
        22: '5.5rem',
      },
      borderRadius: {
        ns:        '8px',
        'ns-card': '12px',
        'ns-lg':   '16px',
        'ns-xl':   '24px',
      },
      boxShadow: {
        ns:         'var(--ns-shadow-sm)',
        'ns-md':    'var(--ns-shadow-md)',
        'ns-lg':    'var(--ns-shadow-lg)',
        'ns-hover': 'var(--ns-shadow-hover)',
        glow:       'var(--ns-shadow-glow)',
      },
      transitionDuration: {
        fast: '120ms',
        base: '200ms',
        slow: '300ms',
      },
      transitionTimingFunction: {
        ns: 'cubic-bezier(0.2, 0, 0, 1)',
      },
      maxWidth: {
        container: '1200px',
      },
    },
  },
  plugins: [],
};
